# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeStart' do
  pod 'AppCenter/Crashes', '~> 1.13.0'
  pod 'AppCenter/Analytics', '~> 1.13.0'
  pod 'AppCenterReactNativeShared', '~> 1.12.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeStart
  pod 'MJExtension'
  pod 'Collector'
#  pod 'react-native-camera', path: '../node_modules/react-native-camera'
#  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  platform :ios, '9.0'

#  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

end
